version: '3'
services:
  # HomeAssistant
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    volumes:
      # Local path where your home assistant config will be stored
      - ./config/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    ports:
      - 8123:8123
    privileged: true
    depends_on:
      - mosquitto # aka mosquitto-mqtt is optional (only if you want to add Zigbee devices and have a zigbee sniffer attached).
      - esphome
      - vscode



  # eclipse-mosquitto (MQTT broker)
  mosquitto:
      image: eclipse-mosquitto
      container_name: mosquitto
      volumes:
        - ./config/mosquitto/config/:/mosquitto/config/
 
      ports:
        - 1883:1883
        - 9001:9001    

  esphome:
    container_name: esphome
    image: esphome/esphome
    volumes:
      - ./config/esphome:/config
      - /etc/localtime:/etc/localtime:ro
      #- /dev/ttyUSB1:/dev/ttyUSB1
      #- /dev/ttyUSB0:/dev/ttyUSB0
    privileged: true
    network_mode: host
    ports:
      - 6052:6052/tcp
      
      


 # Visual Studio code
  vscode:
   container_name: vscode
   image: codercom/code-server:latest
   environment:
     PASSWORD: "${VSCODE_PASSWORD}"
   volumes:
     - .:/home/coder/project
     - ./config/vscode/coder:/home/coder/.local/share/code-server
   ports:
     - "8443:8443"
   command: code-server --auth password --port 8443 --disable-telemetry /home/coder/project
