esphome:
  name: demo-motion-sensor

esp8266:
  board: nodemcuv2

# Enable logging
logger:

debug:
  update_interval: 5s

# Enable Home Assistant API
api:
  encryption:
    key: "vUCBQ6OO1mXOLrsoQNbJwrbwI1X8aqR8Q/ct4R1oYKU="

ota:
  password: "1598bec83f424b09617210773019a178"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Demo-Motion-Sensor"
    password: "hjNaLyTHX56f"

binary_sensor:
  - platform: gpio
    pin: GPIO05
    name: "PIR Sensor"
    device_class: motion
    
captive_portal:
    